---


- hosts: all
  become: true
  tasks: 
  
  - name: List of tasks
    debug: 
      msg: >
           --==Ansible Jinja2 if variable is defined (Where variable is defined) ==--
           {% set example_variable= 'haha' %}
           {% if example_variable is defined -%}
              Example variable is defined
           {% else -%}
              Example variable is not defined
           {% endif %}

