---

- name: Check if mariadb is running 
  ansible.builtin.systemmd:
    name: mariadb
    state: started

    

- name: restart zabbix necessary services 
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  when: ansible_facts.services['zabbix-server']state == 'running'
  loop: 
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm 