---

- name: Check if mariadb is running 
  service:
    name: mariadb
    state: started
    

- name: restart zabbix necessary services 
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  when: ansible_facts.services['zabbix-server']state == 'running'
  loop: 
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm 


- name: check if httpd is running 
  uri:
    url: http://{{ ansible_default_ipv4.address }}/zabbix
    status_code: 200