---

- name: Restart mariadb serivce
  service:
    name: mariadb
    state: restarted
    

- name: restart zabbix necessary services 
  tags: zabbix
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop: 
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm
  when: ansible_facts['os_family'] == 'RedHat'

- name: check if httpd is running 
  uri:
    url: http://{{ ansible_default_ipv4.address }}/zabbix
    status_code: 200