- name: Enable http/https access to Zabbix 
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restart firewalld
  when: ansible_facts['os_family'] == 'RedHat'