# This task ensures that the httpd, MariaDB, zabbix-serverservice is running before proceeding with configuration.
---

- name: Create a new DB name zabbix
  tags: mariadb zabbix
  community.mysql.mysql_db:
    login_unix_socket: "{{ login_unix_socket }}"
    name: "{{ zabbix_dbname }}"
    state: present 
    encoding: utf8mb4
    collation: utf8mb4_bin
  when: ansible_distribution == "CentOS"
  
- name: Create User zabbix@localhost
  tags: mariadb zabbix
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ zabbix_user }}"
    password: "{{ password_zabbix_user }}"
    priv: "zabbix.*:ALL"
    state: present 
  when: ansible_distribution == "CentOS"

- name: Ensure that zabbix schema exist
  tags: mariadb zabbix
  community.mysql.mysql_query:
    login_unix_socket: "{{ login_unix_socket }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ password_zabbix_user }}"
    login_db: zabbix
    query: "SHOW TABLES;"
  register: zabbix_schema_check


- name: Import Zabbix SQL schema
  tags: mariadb zabbix
  community.mysql.mysql_query:
    login_unix_socket: "{{ login_unix_socket }}"
    name: "{{ zabbix_dbname }}"
    state: import
    default_character_set: utf8mb4
    target: /usr/share/zabbix/sql-scripts/mysql/server.sql.gz 
<<<<<<< HEAD
  when: zabbix_schema_check.rc != 0 
=======
  when: zabbix_schema_check.rc != 0
>>>>>>> 39ddb775c0b3f4fe301943bde1de6de031cd0393


- name: Upload template for Zabbix server configuration
  tags: zabbix
  ansible.builtin.template:
    src: zabbix_server_conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix 
    group: zabbix
    mode: '0644'
  notify: restart zabbix necessary services 







#- name: Ensure that zabbix schema exit
#  tags: mariadb zabbix
#  command:
#    cmd: mysql -u{{ zabbix_user }} -p{{ password_zabbix_user }}" zabbix -e "show tables;"
#  changed_when: false 
#  register: zabbix_schema_check
#  when: ansible_distribution == "CentOS"


#- name: Import Zabbix SQL
#  tags: mariadb zabbix
#  zabbix_dbname: zabbix
#  shell: "zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u{{ zabbix_user }} {{ zabbix_dbname }}"
#  environment:
#    MYSQL_PWD: "{{ password_zabbix_user }}"
# Run this task only if the schema check failed
# when: zabbix_schema_check.rc != 0 
