# This task ensures that the httpd, MariaDB, zabbix-serverservice is running before proceeding with configuration.
---

- name: Create a new DB name zabbix
  tags: mariadb zabbix
  community.mysql.mysql_db:
# login_unix_socket: "{{ login_unix_socket }}"
    name: zabbix
    state: present 
    encoding: utf8mb4
    collation: utf8mb4_bin
  when: ansible_distribution == "CentOS"
  
- name: Create User zabbix@localhost
  tags: mariadb zabbix
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: zabbix
    password: zabbix
    priv: "zabbix.*:ALL"
    state: present 
  when: ansible_distribution == "CentOS"

- name: Ensure that zabbix schema exit
  tags: mariadb zabbix
  command:
    cmd: mysql -uzabbix -pzabbix zabbix -e "show tables;"
  changed_when: false 
  register: zabbix_schema_check
  when: ansible_distribution == "CentOS"


- name: Import Zabbix SQL
  tags: mariadb zabbix
  shell: "{{ zabbix_schema }}"
  environment:
    MYSQL_PWD: "zabbix"
# Run this task only if the schema check failed
  when: zabbix_schema_check.rc != 0 