# This task ensures that the httpd, MariaDB, zabbix-serverservice is running before proceeding with configuration.
- name: Start mariadb service 
  tags: mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: Create a new DB name zabbix
  tags: mariadb zabbix
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: zabbix
    state: present 
    encoding: utf8mb4
    collation: utf8mb4_bin
  when: ansible_distribution == "CentOS"
  
- name: Create User zabbix@localhost
  tags: mariadb zabbix
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: zabbix
    password: zabbix
    priv: "zabbix.*:ALL"
    state: present 
  when: ansible_distribution == "CentOS"

- name: Import Zabbix SQL
  shell: zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix zabbix
  environment:
    MYSQL_PWD: "cokolada"
