---

- name: Install zabbix repository to CentOS 9
  tags: zabbix installation 
  dnf:
    name: "rpm -Uvh https://repo.zabbix.com/zabbix/7.4/release/centos/9/noarch/zabbix-release-latest-7.4.el9.noarch.rpm"
    state: present 
    async: yes
    poll: 30
  when: ansible_distribution == "CentOS"

- name: Install nececery packages
  package: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
    async: 600
    poll: 30
  when: ansible_distribution == "CentOS"
  loop: "{{ zabbix_packages }}" 
