- name: Install zabbix rpm from a remote repo
  ansible.builtin.dnf:
    name: 'https://repo.zabbix.com/zabbix/7.4/release/centos/9/noarch/zabbix-release-latest-7.4.el9.noarch.rpm'
    state: present
    validate_certs: true


- name: Install nececery packages
  tags: zabbix
  dnf: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
  loop: "{{ zabbix_packages }}" 
