---
# tasks file for zabbix role
# This file includes tasks for installing Zabbix, configuring MariaDB, and setting up Zabbix.

- name: Include package_installation 
  include_tasks: package_installation.yml
  tags: zabbix 

- name: Enable and start MariaDB, httpd services
  tags: zabbix
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"
  loop: "{{ startup_sevices }}"

- name: include mariadb configuration tasks
  include_tasks: mariadb_configuraion.yml
  tags: mariadb zabbix

- name: Start nececery zabbix services
  tags: zabbix
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ zabbix_necessary_services}}"
  when: ansible_distribution == "CentOS" 

- name: Check if httpd server is running 
  uri:
    url: http://{{ ansible_default_ipv4.address }}/zabbix
    status_code: 200
  register: httpd_check
  when: ansible_facts['os_family'] == 'RedHat'

