# This task ensures that the httpd, MariaDB, zabbix-serverservice is running before proceeding with configuration.
---

- name: Create a new DB name zabbix
  tags: mariadb zabbix
  collections: 
    - community.mysql

  community.mysql.mysql_db:
    login_unix_socket: "{{ login_unix_socket }}"
    name: "{{ zabbix_dbname }}"
    state: present 
    encoding: utf8mb4
    collation: utf8mb4_bin
  when: ansible_distribution == "CentOS"

# This created a error while importing the schema, so I added the task to set this variable and it worked.
- name: Set log_bin_trust_function_creators to 1 for zabbix database
  tags: mariadb zabbix
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    login_unix_socket: /var/lib/mysql/mysql.sock
    value: 1
    login_user: root
    login_password: "{{ root_password_mariadb }}"
  when: ansible_distribution == "CentOS"
  
- name: Create user zabbix@localhost
  tags: mariadb zabbix
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ zabbix_user }}"
    password: "{{ password_zabbix_user }}"
    priv: "{{zabbix_dbname}}.*:ALL"
    state: present 
  when: ansible_distribution == "CentOS"

- name: Ensure that zabbix schema exist
  tags: mariadb zabbix
  community.mysql.mysql_query:
    login_unix_socket: "{{ login_unix_socket }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ password_zabbix_user }}"
    login_db: "{{ zabbix_dbname }}"
    query: "SHOW TABLES;"
  register: zabbix_schema_check

- name: Import Zabbix SQL schema
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ zabbix_dbname }}"
    state: import
    target: /usr/share/zabbix/sql-scripts/mysql/server.sql.gz
    login_user: "{{ zabbix_user }}"
    login_password: "{{ password_zabbix_user }}"
  when: zabbix_schema_check.failed

- name: Upload template for Zabbix server configuration
  tags: zabbix
  ansible.builtin.template:
    src: zabbix_server_conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix 
    group: zabbix
    mode: '0644'
  notify: restart zabbix necessary services 

