---

- name: Add zabbix rpm from a remote repo
  tags: zabbix
  ansible.builtin.dnf:
    name: 'https://repo.zabbix.com/zabbix/7.4/release/centos/9/noarch/zabbix-release-latest-7.4.el9.noarch.rpm'
    state: present
    validate_certs: true
    disable_gpg_check: true
  when: ansible_facts['os_family']== "RedHat"
  
- name: Install Zabbix server, frontend, agent and database packages
  tags: zabbix
  ansible.builtin.dnf: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
  loop: "{{ zabbix_packages }}" 
