zabbix_packages: 
  - zabbix-server-mysql 
  - zabbix-web-mysql 
  - zabbix-apache-conf
  - zabbix-sql-scripts
  - zabbix-selinux-policy
  - zabbix-agent
  - mariadb 

password_zabbix_db: cokolada
password_zabbix_user: cokolada
zabbix_user: zabbix 
zabbix_dbname: zabbix